import express from "express";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import path from "path";

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Increase payload limit for base64 images
  app.use(express.json({ limit: '50mb' }));

  // API route for background removal
  app.post("/api/remove-background", async (req, res) => {
    try {
      const { image, apiKey } = req.body;
      if (!image) {
        return res.status(400).json({ error: "Image is required" });
      }

      const ai = new GoogleGenAI({ apiKey: apiKey || process.env.GEMINI_API_KEY || '' });
      
      const base64Data = image.includes(',') ? image.split(',')[1] : image;
      const mimeType = image.includes(';') ? image.split(';')[0].split(':')[1] : 'image/jpeg';

      const model = "gemini-2.5-flash-image"; 

      const promptText = `You are an expert product photo retoucher. Your task is to extract the main product (a mobile phone display/screen) and place it on a pure white background (#FFFFFF) with a subtle soft shadow. 
      CRITICAL INSTRUCTIONS: 
      1. DO NOT alter, add, or hallucinate any hardware features. DO NOT add fake camera holes, notches, or buttons. Keep the exact original shape and hardware exactly as it is in the original photo. 
      2. The product may have a protective brand sticker. Keep the sticker and all original text/logos exactly as they are.
      3. Carefully remove any air bubbles, dust, or wrinkles from the sticker/screen surface to make it look brand new, clean, and perfectly smooth.
      4. Ensure perfectly clean edges around the product.`;

      const generatePromise = ai.models.generateContent({
          model: model,
          contents: {
              parts: [
                  { 
                      inlineData: { 
                          data: base64Data, 
                          mimeType: mimeType 
                      } 
                  },
                  { text: promptText },
              ],
          },
      });

      // 30 second timeout for the AI call
      const timeoutPromise = new Promise<never>((_, reject) => {
          setTimeout(() => reject(new Error("AI processing timed out. Please try again.")), 30000);
      });

      const response = await Promise.race([generatePromise, timeoutPromise]);

      const parts = response.candidates?.[0]?.content?.parts;
      if (parts) {
          for (const part of parts) {
              if (part.inlineData) {
                  return res.json({ image: `data:${part.inlineData.mimeType};base64,${part.inlineData.data}` });
              }
          }
      }
      
      throw new Error("No image generated by AI");

    } catch (error: any) {
      console.error("AI Background Removal Failed:", error);
      res.status(500).json({ error: error.message || "Failed to process image" });
    }
  });

  // API route for Magic Studio
  app.post("/api/magic-studio", async (req, res) => {
    try {
      const { image, prompt, apiKey } = req.body;
      if (!image) {
        return res.status(400).json({ error: "Image is required" });
      }

      const ai = new GoogleGenAI({ apiKey: apiKey || process.env.GEMINI_API_KEY || '' });
      
      const base64Data = image.includes(',') ? image.split(',')[1] : image;
      const mimeType = image.includes(';') ? image.split(';')[0].split(':')[1] : 'image/jpeg';

      const model = "gemini-2.5-flash-image"; 
      
      const fullPrompt = `Generate a professional product photography version of this image. 
      Keep the main product exactly as is, but place it in a new environment: ${prompt}.
      Ensure the lighting matches the new environment. High quality, photorealistic, 4k.`;

      const generatePromise = ai.models.generateContent({
          model: model,
          contents: {
              parts: [
                  { 
                      inlineData: { 
                          data: base64Data, 
                          mimeType: mimeType 
                      } 
                  },
                  { text: fullPrompt },
              ],
          },
      });

      // 30 second timeout for the AI call
      const timeoutPromise = new Promise<never>((_, reject) => {
          setTimeout(() => reject(new Error("AI processing timed out. Please try again.")), 30000);
      });

      const response = await Promise.race([generatePromise, timeoutPromise]);

      const parts = response.candidates?.[0]?.content?.parts;
      if (parts) {
          for (const part of parts) {
              if (part.inlineData) {
                  return res.json({ image: `data:${part.inlineData.mimeType};base64,${part.inlineData.data}` });
              }
          }
      }
      
      throw new Error("No image generated by AI");

    } catch (error: any) {
      console.error("Magic Studio Generation Failed:", error);
      res.status(500).json({ error: error.message || "Failed to generate image" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
