
import { GoogleGenAI } from "@google/genai";

// Helper for delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Generates a professional product image using Gemini AI (Magic Studio).
 * This uses the remote API and requires an API Key.
 */
export const generateMagicStudioImage = async (base64Image: string, prompt: string): Promise<string> => {
    try {
        console.log("✨ Generating Magic Studio Image via Gemini (Frontend)...");
        
        // Resize image to prevent memory crashes on mobile
        const resizedBase64 = await resizeImage(base64Image, 800);

        const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });
        
        const base64Data = resizedBase64.includes(',') ? resizedBase64.split(',')[1] : resizedBase64;
        const mimeType = resizedBase64.includes(';') ? resizedBase64.split(';')[0].split(':')[1] : 'image/jpeg';

        const fullPrompt = `Task: Background Removal and Studio Enhancement.
Input: A product image.
Goal: Extract the EXACT product and place it on a clean white background (#FFFFFF).

CRITICAL CONSTRAINTS:
1. DO NOT RE-GENERATE, REDRAW, OR ALTER the product's shape, color, texture, or details.
2. The product in the output must be a literal pixel-for-pixel cutout of the original.
3. Apply a subtle "Studio Effect" by gently evening out the lighting on the product ONLY (no over-exposure).
4. The background MUST be pure white solid color.
5. NO SHADOWS or reflections should be added.`;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-image",
            contents: {
                parts: [
                    { 
                        inlineData: { 
                            data: base64Data, 
                            mimeType: mimeType 
                        } 
                    },
                    { text: fullPrompt },
                ],
            },
            config: {
                temperature: 0.1,
                topP: 1,
                topK: 1,
            }
        });

        const parts = response.candidates?.[0]?.content?.parts;
        if (parts) {
            for (const part of parts) {
                if (part.inlineData) {
                    return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                }
            }
        }
        
        throw new Error("No image generated by AI");

    } catch (error) {
        console.error("Magic Studio Generation Failed:", error);
        throw error;
    }
};

export const removeBackgroundWithAI = async (base64Image: string, onProgress?: (msg: string) => void): Promise<string> => {
    try {
        console.log("✨ Removing background using Gemini AI (Frontend)...");
        if (onProgress) onProgress("Preparing image...");
        
        // Resize image to prevent memory crashes on mobile
        const resizedBase64 = await resizeImage(base64Image, 800);
        
        if (onProgress) onProgress("Uploading image to AI...");
        
        const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });
        
        const base64Data = resizedBase64.includes(',') ? resizedBase64.split(',')[1] : resizedBase64;
        const mimeType = resizedBase64.includes(';') ? resizedBase64.split(';')[0].split(':')[1] : 'image/jpeg';

        const promptText = `Your task is purely background removal.
1. Perform a pixel-precise cutout of the main product in the image.
2. Place the cutout object onto a solid white background (#FFFFFF).
3. Do NOT add, change, or re-render any part of the product.
4. Keep the image lighting and product structure exactly as they appear in the original input. 
5. DO NOT generate a shadow. Return ONLY the product image on plain white background.`;

        if (onProgress) onProgress("Processing image with AI...");

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-image",
            contents: {
                parts: [
                    { 
                        inlineData: { 
                            data: base64Data, 
                            mimeType: mimeType 
                        } 
                    },
                    { text: promptText },
                ],
            },
            config: {
                temperature: 0.1,
                topP: 1,
                topK: 1,
            }
        });

        if (onProgress) onProgress("Finalizing...");

        // Iterate through all parts to find the image part as recommended by the skill
        if (response.candidates?.[0]?.content?.parts) {
            for (const part of response.candidates[0].content.parts) {
                if (part.inlineData) {
                    return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                }
            }
        }
        
        throw new Error("No image generated by AI");

    } catch (error) {
        console.error("AI Background Removal Failed:", error);
        throw error;
    }
};

// Helper function to resize image before sending to AI
function resizeImage(base64Str: string, maxWidth: number): Promise<string> {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.src = base64Str;
        img.onload = () => {
            const canvas = document.createElement('canvas');
            let width = img.width;
            let height = img.height;

            if (width > maxWidth) {
                height = Math.round((height * maxWidth) / width);
                width = maxWidth;
            }

            canvas.width = width;
            canvas.height = height;
            const ctx = canvas.getContext('2d');
            if (!ctx) {
                resolve(base64Str);
                return;
            }
            ctx.drawImage(img, 0, 0, width, height);
            resolve(canvas.toDataURL('image/jpeg', 0.8));
        };
        img.onerror = (err) => reject(err);
    });
};

export const verifyPaymentScreenshot = async (imageBase64: string, expectedAmount: number): Promise<any> => {
    // Mock verification for now
    await new Promise(resolve => setTimeout(resolve, 1000));
    return {
        isValid: true,
        amount: expectedAmount,
        transactionId: `TXN_${Date.now()}`,
        date: new Date().toISOString()
    };
};
