
import React from 'react';
import { ShoppingBag, Smartphone, Battery, Cpu, Wrench, Headphones, Grid, SmartphoneNfc, Zap, Camera, HardDrive, Layers, Box, Settings } from 'lucide-react';

export const DASHBOARD_THEME = {
  ticker: {
    container: "bg-slate-50 border border-slate-100",
    iconBg: "bg-slate-900",
    text: "text-slate-900",
    time: "text-slate-400"
  },
  search: {
    activeCategory: "bg-slate-900 text-white shadow-lg shadow-slate-200",
    inactiveCategory: "bg-white border border-gray-100 text-gray-500 hover:bg-gray-50"
  }
};

export const DASHBOARD_TEXTS = {
    TAB_MARKET: "Market",
    TAB_ACTIVITY: "My Shop",
    NO_ITEMS: "No items listed yet.",
    NO_MY_ITEMS: "No items in your shop."
};

export const CATEGORIES = [
  { id: 'mobile', label: 'Mobiles', icon: <SmartphoneNfc size={20} /> }, 
  { id: 'display', label: 'Display', icon: <Smartphone size={20} /> }, 
  { id: 'battery', label: 'Battery', icon: <Battery size={20} /> },
  { id: 'board', label: 'Motherboard', icon: <Cpu size={20} /> },
  { id: 'ic', label: 'IC & Chips', icon: <Layers size={20} /> },
  { id: 'charging', label: 'Charging CC', icon: <Zap size={20} /> },
  { id: 'camera', label: 'Camera', icon: <Camera size={20} /> },
  { id: 'body', label: 'Housing/Body', icon: <Box size={20} /> },
  { id: 'frame', label: 'Frame', icon: <Grid size={20} /> },
  { id: 'tools', label: 'Tools', icon: <Wrench size={20} /> },
  { id: 'accessories', label: 'Accessories', icon: <Headphones size={20} /> },
  { id: 'other', label: 'Other', icon: <Settings size={20} /> },
];

// International Style: White Backgrounds with Brand Specific Colors for Text/Icon
export const BRANDS = [
  { id: 'xiaomi', label: 'Xiaomi', color: 'text-[#FF6900]', bg: 'bg-[#FF6900]/10', border: 'hover:border-[#FF6900]' }, 
  { id: 'samsung', label: 'Samsung', color: 'text-[#1428A0]', bg: 'bg-[#1428A0]/10', border: 'hover:border-[#1428A0]' }, 
  { id: 'vivo', label: 'Vivo', color: 'text-[#415FFF]', bg: 'bg-[#415FFF]/10', border: 'hover:border-[#415FFF]' }, 
  { id: 'oppo', label: 'Oppo', color: 'text-[#007F3E]', bg: 'bg-[#007F3E]/10', border: 'hover:border-[#007F3E]' }, 
  { id: 'realme', label: 'Realme', color: 'text-[#FFC915]', bg: 'bg-[#FFC915]/10', border: 'hover:border-[#FFC915]' }, 
  { id: 'oneplus', label: 'OnePlus', color: 'text-[#F00028]', bg: 'bg-[#F00028]/10', border: 'hover:border-[#F00028]' }, 
  { id: 'apple', label: 'Apple', color: 'text-black', bg: 'bg-gray-100', border: 'hover:border-black' },
  { id: 'motorola', label: 'Motorola', color: 'text-[#5C92FA]', bg: 'bg-[#5C92FA]/10', border: 'hover:border-[#5C92FA]' },
  { id: 'google', label: 'Google', color: 'text-[#4285F4]', bg: 'bg-[#4285F4]/10', border: 'hover:border-[#4285F4]' },
  { id: 'nothing', label: 'Nothing', color: 'text-black', bg: 'bg-gray-200', border: 'hover:border-gray-400' },
  { id: 'infinix', label: 'Infinix', color: 'text-[#000000]', bg: 'bg-green-100', border: 'hover:border-green-500' },
  { id: 'tecno', label: 'Tecno', color: 'text-[#000000]', bg: 'bg-blue-100', border: 'hover:border-blue-500' },
  { id: 'other', label: 'Other', color: 'text-gray-600', bg: 'bg-gray-100', border: 'hover:border-gray-300' },
];

export const POPULAR_MODELS = [
    // ================= APPLE =================
    { id: 'ip-15-promax', name: 'iPhone 15 Pro Max', brand: 'apple' },
    { id: 'ip-15-pro', name: 'iPhone 15 Pro', brand: 'apple' },
    { id: 'ip-15-plus', name: 'iPhone 15 Plus', brand: 'apple' },
    { id: 'ip-15', name: 'iPhone 15', brand: 'apple' },
    { id: 'ip-14-promax', name: 'iPhone 14 Pro Max', brand: 'apple' },
    { id: 'ip-14-pro', name: 'iPhone 14 Pro', brand: 'apple' },
    { id: 'ip-14-plus', name: 'iPhone 14 Plus', brand: 'apple' },
    { id: 'ip-14', name: 'iPhone 14', brand: 'apple' },
    { id: 'ip-13-promax', name: 'iPhone 13 Pro Max', brand: 'apple' },
    { id: 'ip-13-pro', name: 'iPhone 13 Pro', brand: 'apple' },
    { id: 'ip-13-mini', name: 'iPhone 13 Mini', brand: 'apple' },
    { id: 'ip-13', name: 'iPhone 13', brand: 'apple' },
    { id: 'ip-12-promax', name: 'iPhone 12 Pro Max', brand: 'apple' },
    { id: 'ip-12-pro', name: 'iPhone 12 Pro', brand: 'apple' },
    { id: 'ip-12-mini', name: 'iPhone 12 Mini', brand: 'apple' },
    { id: 'ip-12', name: 'iPhone 12', brand: 'apple' },
    { id: 'ip-11-promax', name: 'iPhone 11 Pro Max', brand: 'apple' },
    { id: 'ip-11-pro', name: 'iPhone 11 Pro', brand: 'apple' },
    { id: 'ip-11', name: 'iPhone 11', brand: 'apple' },
    { id: 'ip-xs-max', name: 'iPhone XS Max', brand: 'apple' },
    { id: 'ip-xs', name: 'iPhone XS', brand: 'apple' },
    { id: 'ip-xr', name: 'iPhone XR', brand: 'apple' },
    { id: 'ip-x', name: 'iPhone X', brand: 'apple' },
    { id: 'ip-8-plus', name: 'iPhone 8 Plus', brand: 'apple' },
    { id: 'ip-8', name: 'iPhone 8', brand: 'apple' },
    { id: 'ip-7-plus', name: 'iPhone 7 Plus', brand: 'apple' },
    { id: 'ip-7', name: 'iPhone 7', brand: 'apple' },
    { id: 'ip-6s-plus', name: 'iPhone 6S Plus', brand: 'apple' },
    { id: 'ip-6s', name: 'iPhone 6S', brand: 'apple' },
    { id: 'ip-6-plus', name: 'iPhone 6 Plus', brand: 'apple' },
    { id: 'ip-6', name: 'iPhone 6', brand: 'apple' },
    { id: 'ip-se-2020', name: 'iPhone SE 2020', brand: 'apple' },
    { id: 'ip-se-2022', name: 'iPhone SE 2022', brand: 'apple' },

    // ================= SAMSUNG =================
    // S Series
    { id: 's24-ultra', name: 'Samsung S24 Ultra', brand: 'samsung' },
    { id: 's24-plus', name: 'Samsung S24 Plus', brand: 'samsung' },
    { id: 's24', name: 'Samsung S24', brand: 'samsung' },
    { id: 's23-ultra', name: 'Samsung S23 Ultra', brand: 'samsung' },
    { id: 's23-fe', name: 'Samsung S23 FE', brand: 'samsung' },
    { id: 's23', name: 'Samsung S23', brand: 'samsung' },
    { id: 's22-ultra', name: 'Samsung S22 Ultra', brand: 'samsung' },
    { id: 's22-plus', name: 'Samsung S22 Plus', brand: 'samsung' },
    { id: 's22', name: 'Samsung S22', brand: 'samsung' },
    { id: 's21-ultra', name: 'Samsung S21 Ultra', brand: 'samsung' },
    { id: 's21-fe', name: 'Samsung S21 FE', brand: 'samsung' },
    { id: 's21-plus', name: 'Samsung S21 Plus', brand: 'samsung' },
    { id: 's21', name: 'Samsung S21', brand: 'samsung' },
    { id: 's20-ultra', name: 'Samsung S20 Ultra', brand: 'samsung' },
    { id: 's20-fe', name: 'Samsung S20 FE', brand: 'samsung' },
    { id: 's20-plus', name: 'Samsung S20 Plus', brand: 'samsung' },
    { id: 's20', name: 'Samsung S20', brand: 'samsung' },
    { id: 's10-plus', name: 'Samsung S10 Plus', brand: 'samsung' },
    { id: 's10', name: 'Samsung S10', brand: 'samsung' },
    { id: 's9-plus', name: 'Samsung S9 Plus', brand: 'samsung' },
    { id: 's9', name: 'Samsung S9', brand: 'samsung' },
    { id: 's8-plus', name: 'Samsung S8 Plus', brand: 'samsung' },
    { id: 's8', name: 'Samsung S8', brand: 'samsung' },
    
    // Note Series
    { id: 'note-20-ultra', name: 'Samsung Note 20 Ultra', brand: 'samsung' },
    { id: 'note-20', name: 'Samsung Note 20', brand: 'samsung' },
    { id: 'note-10-plus', name: 'Samsung Note 10 Plus', brand: 'samsung' },
    { id: 'note-10-lite', name: 'Samsung Note 10 Lite', brand: 'samsung' },
    { id: 'note-10', name: 'Samsung Note 10', brand: 'samsung' },
    { id: 'note-9', name: 'Samsung Note 9', brand: 'samsung' },
    { id: 'note-8', name: 'Samsung Note 8', brand: 'samsung' },

    // A Series (Most Common Spares)
    { id: 'a55', name: 'Samsung A55 5G', brand: 'samsung' },
    { id: 'a54', name: 'Samsung A54 5G', brand: 'samsung' },
    { id: 'a53', name: 'Samsung A53 5G', brand: 'samsung' },
    { id: 'a52s', name: 'Samsung A52s 5G', brand: 'samsung' },
    { id: 'a52', name: 'Samsung A52', brand: 'samsung' },
    { id: 'a51', name: 'Samsung A51', brand: 'samsung' },
    { id: 'a50s', name: 'Samsung A50s', brand: 'samsung' },
    { id: 'a50', name: 'Samsung A50', brand: 'samsung' },
    { id: 'a35', name: 'Samsung A35 5G', brand: 'samsung' },
    { id: 'a34', name: 'Samsung A34 5G', brand: 'samsung' },
    { id: 'a33', name: 'Samsung A33 5G', brand: 'samsung' },
    { id: 'a32', name: 'Samsung A32', brand: 'samsung' },
    { id: 'a31', name: 'Samsung A31', brand: 'samsung' },
    { id: 'a30s', name: 'Samsung A30s', brand: 'samsung' },
    { id: 'a30', name: 'Samsung A30', brand: 'samsung' },
    { id: 'a25', name: 'Samsung A25 5G', brand: 'samsung' },
    { id: 'a24', name: 'Samsung A24', brand: 'samsung' },
    { id: 'a23', name: 'Samsung A23', brand: 'samsung' },
    { id: 'a22-5g', name: 'Samsung A22 5G', brand: 'samsung' },
    { id: 'a22', name: 'Samsung A22 4G', brand: 'samsung' },
    { id: 'a21s', name: 'Samsung A21s', brand: 'samsung' },
    { id: 'a20s', name: 'Samsung A20s', brand: 'samsung' },
    { id: 'a20', name: 'Samsung A20', brand: 'samsung' },
    { id: 'a15-5g', name: 'Samsung A15 5G', brand: 'samsung' },
    { id: 'a14-5g', name: 'Samsung A14 5G', brand: 'samsung' },
    { id: 'a13', name: 'Samsung A13', brand: 'samsung' },
    { id: 'a12', name: 'Samsung A12', brand: 'samsung' },
    { id: 'a10s', name: 'Samsung A10s', brand: 'samsung' },
    { id: 'a10', name: 'Samsung A10', brand: 'samsung' },
    { id: 'a05s', name: 'Samsung A05s', brand: 'samsung' },
    { id: 'a05', name: 'Samsung A05', brand: 'samsung' },
    { id: 'a04s', name: 'Samsung A04s', brand: 'samsung' },
    { id: 'a03s', name: 'Samsung A03s', brand: 'samsung' },
    
    // M Series
    { id: 'm55', name: 'Samsung M55 5G', brand: 'samsung' },
    { id: 'm52', name: 'Samsung M52 5G', brand: 'samsung' },
    { id: 'm51', name: 'Samsung M51', brand: 'samsung' },
    { id: 'm42', name: 'Samsung M42 5G', brand: 'samsung' },
    { id: 'm34', name: 'Samsung M34 5G', brand: 'samsung' },
    { id: 'm33', name: 'Samsung M33 5G', brand: 'samsung' },
    { id: 'm32', name: 'Samsung M32', brand: 'samsung' },
    { id: 'm31s', name: 'Samsung M31s', brand: 'samsung' },
    { id: 'm31', name: 'Samsung M31', brand: 'samsung' },
    { id: 'm30s', name: 'Samsung M30s', brand: 'samsung' },
    { id: 'm30', name: 'Samsung M30', brand: 'samsung' },
    { id: 'm21', name: 'Samsung M21', brand: 'samsung' },
    { id: 'm14', name: 'Samsung M14 5G', brand: 'samsung' },
    { id: 'm13', name: 'Samsung M13', brand: 'samsung' },
    { id: 'm12', name: 'Samsung M12', brand: 'samsung' },
    { id: 'm11', name: 'Samsung M11', brand: 'samsung' },
    { id: 'm04', name: 'Samsung M04', brand: 'samsung' },
    { id: 'm02', name: 'Samsung M02', brand: 'samsung' },
    { id: 'm01', name: 'Samsung M01', brand: 'samsung' },

    // F Series
    { id: 'f62', name: 'Samsung F62', brand: 'samsung' },
    { id: 'f54', name: 'Samsung F54 5G', brand: 'samsung' },
    { id: 'f41', name: 'Samsung F41', brand: 'samsung' },
    { id: 'f23', name: 'Samsung F23', brand: 'samsung' },
    { id: 'f22', name: 'Samsung F22', brand: 'samsung' },
    { id: 'f15', name: 'Samsung F15 5G', brand: 'samsung' },
    { id: 'f14', name: 'Samsung F14 5G', brand: 'samsung' },
    { id: 'f13', name: 'Samsung F13', brand: 'samsung' },
    
    // J Series (Legacy Spares)
    { id: 'j8', name: 'Samsung J8', brand: 'samsung' },
    { id: 'j7-prime', name: 'Samsung J7 Prime', brand: 'samsung' },
    { id: 'j7-pro', name: 'Samsung J7 Pro', brand: 'samsung' },
    { id: 'j7-max', name: 'Samsung J7 Max', brand: 'samsung' },
    { id: 'j7-nxt', name: 'Samsung J7 Nxt', brand: 'samsung' },
    { id: 'j7-2016', name: 'Samsung J7 (2016)', brand: 'samsung' },
    { id: 'j6-plus', name: 'Samsung J6 Plus', brand: 'samsung' },
    { id: 'j6', name: 'Samsung J6', brand: 'samsung' },
    { id: 'j5-prime', name: 'Samsung J5 Prime', brand: 'samsung' },
    { id: 'j4-plus', name: 'Samsung J4 Plus', brand: 'samsung' },
    { id: 'j4', name: 'Samsung J4', brand: 'samsung' },
    { id: 'j2-core', name: 'Samsung J2 Core', brand: 'samsung' },
    { id: 'j2-pro', name: 'Samsung J2 Pro', brand: 'samsung' },
    { id: 'j2-2018', name: 'Samsung J2 (2018)', brand: 'samsung' },

    // ================= XIAOMI / REDMI / POCO =================
    // Redmi Note Series
    { id: 'rn-13-pro-plus', name: 'Redmi Note 13 Pro+', brand: 'xiaomi' },
    { id: 'rn-13-pro', name: 'Redmi Note 13 Pro', brand: 'xiaomi' },
    { id: 'rn-13', name: 'Redmi Note 13', brand: 'xiaomi' },
    { id: 'rn-12-pro-plus', name: 'Redmi Note 12 Pro+', brand: 'xiaomi' },
    { id: 'rn-12-pro', name: 'Redmi Note 12 Pro', brand: 'xiaomi' },
    { id: 'rn-12', name: 'Redmi Note 12 5G', brand: 'xiaomi' },
    { id: 'rn-12-4g', name: 'Redmi Note 12 4G', brand: 'xiaomi' },
    { id: 'rn-11-pro-plus', name: 'Redmi Note 11 Pro+', brand: 'xiaomi' },
    { id: 'rn-11-pro', name: 'Redmi Note 11 Pro', brand: 'xiaomi' },
    { id: 'rn-11-t', name: 'Redmi Note 11T 5G', brand: 'xiaomi' },
    { id: 'rn-11-s', name: 'Redmi Note 11S', brand: 'xiaomi' },
    { id: 'rn-11', name: 'Redmi Note 11', brand: 'xiaomi' },
    { id: 'rn-10-pro-max', name: 'Redmi Note 10 Pro Max', brand: 'xiaomi' },
    { id: 'rn-10-pro', name: 'Redmi Note 10 Pro', brand: 'xiaomi' },
    { id: 'rn-10-s', name: 'Redmi Note 10S', brand: 'xiaomi' },
    { id: 'rn-10-t', name: 'Redmi Note 10T 5G', brand: 'xiaomi' },
    { id: 'rn-10', name: 'Redmi Note 10', brand: 'xiaomi' },
    { id: 'rn-9-pro-max', name: 'Redmi Note 9 Pro Max', brand: 'xiaomi' },
    { id: 'rn-9-pro', name: 'Redmi Note 9 Pro', brand: 'xiaomi' },
    { id: 'rn-9', name: 'Redmi Note 9', brand: 'xiaomi' },
    { id: 'rn-8-pro', name: 'Redmi Note 8 Pro', brand: 'xiaomi' },
    { id: 'rn-8', name: 'Redmi Note 8', brand: 'xiaomi' },
    { id: 'rn-7-pro', name: 'Redmi Note 7 Pro', brand: 'xiaomi' },
    { id: 'rn-7-s', name: 'Redmi Note 7S', brand: 'xiaomi' },
    { id: 'rn-7', name: 'Redmi Note 7', brand: 'xiaomi' },
    { id: 'rn-6-pro', name: 'Redmi Note 6 Pro', brand: 'xiaomi' },
    { id: 'rn-5-pro', name: 'Redmi Note 5 Pro', brand: 'xiaomi' },
    { id: 'rn-5', name: 'Redmi Note 5', brand: 'xiaomi' },
    { id: 'rn-4', name: 'Redmi Note 4', brand: 'xiaomi' },

    // Redmi Number Series
    { id: 'mi-13c', name: 'Redmi 13C', brand: 'xiaomi' },
    { id: 'mi-12', name: 'Redmi 12 5G', brand: 'xiaomi' },
    { id: 'mi-12c', name: 'Redmi 12C', brand: 'xiaomi' },
    { id: 'mi-11-prime', name: 'Redmi 11 Prime', brand: 'xiaomi' },
    { id: 'mi-10', name: 'Redmi 10', brand: 'xiaomi' },
    { id: 'mi-10-prime', name: 'Redmi 10 Prime', brand: 'xiaomi' },
    { id: 'mi-10a', name: 'Redmi 10A', brand: 'xiaomi' },
    { id: 'mi-9-power', name: 'Redmi 9 Power', brand: 'xiaomi' },
    { id: 'mi-9-prime', name: 'Redmi 9 Prime', brand: 'xiaomi' },
    { id: 'mi-9', name: 'Redmi 9', brand: 'xiaomi' },
    { id: 'mi-9a', name: 'Redmi 9A', brand: 'xiaomi' },
    { id: 'mi-9i', name: 'Redmi 9i', brand: 'xiaomi' },
    { id: 'mi-8', name: 'Redmi 8', brand: 'xiaomi' },
    { id: 'mi-8a', name: 'Redmi 8A', brand: 'xiaomi' },
    { id: 'mi-8a-dual', name: 'Redmi 8A Dual', brand: 'xiaomi' },
    { id: 'mi-7', name: 'Redmi 7', brand: 'xiaomi' },
    { id: 'mi-7a', name: 'Redmi 7A', brand: 'xiaomi' },
    { id: 'mi-6', name: 'Redmi 6', brand: 'xiaomi' },
    { id: 'mi-6a', name: 'Redmi 6A', brand: 'xiaomi' },
    { id: 'mi-5a', name: 'Redmi 5A', brand: 'xiaomi' },
    { id: 'mi-4a', name: 'Redmi 4A', brand: 'xiaomi' },
    { id: 'mi-y2', name: 'Redmi Y2', brand: 'xiaomi' },
    { id: 'mi-y3', name: 'Redmi Y3', brand: 'xiaomi' },

    // POCO
    { id: 'poco-x6-pro', name: 'Poco X6 Pro', brand: 'xiaomi' },
    { id: 'poco-x6', name: 'Poco X6', brand: 'xiaomi' },
    { id: 'poco-x5-pro', name: 'Poco X5 Pro', brand: 'xiaomi' },
    { id: 'poco-x5', name: 'Poco X5', brand: 'xiaomi' },
    { id: 'poco-x4-pro', name: 'Poco X4 Pro 5G', brand: 'xiaomi' },
    { id: 'poco-x3-pro', name: 'Poco X3 Pro', brand: 'xiaomi' },
    { id: 'poco-x3', name: 'Poco X3', brand: 'xiaomi' },
    { id: 'poco-x2', name: 'Poco X2', brand: 'xiaomi' },
    { id: 'poco-f5', name: 'Poco F5', brand: 'xiaomi' },
    { id: 'poco-f4', name: 'Poco F4 5G', brand: 'xiaomi' },
    { id: 'poco-f3-gt', name: 'Poco F3 GT', brand: 'xiaomi' },
    { id: 'poco-f1', name: 'Poco F1', brand: 'xiaomi' },
    { id: 'poco-m6-pro', name: 'Poco M6 Pro 5G', brand: 'xiaomi' },
    { id: 'poco-m6', name: 'Poco M6 5G', brand: 'xiaomi' },
    { id: 'poco-m5', name: 'Poco M5', brand: 'xiaomi' },
    { id: 'poco-m4-pro-5g', name: 'Poco M4 Pro 5G', brand: 'xiaomi' },
    { id: 'poco-m4-pro-4g', name: 'Poco M4 Pro 4G', brand: 'xiaomi' },
    { id: 'poco-m3-pro', name: 'Poco M3 Pro 5G', brand: 'xiaomi' },
    { id: 'poco-m3', name: 'Poco M3', brand: 'xiaomi' },
    { id: 'poco-m2-pro', name: 'Poco M2 Pro', brand: 'xiaomi' },
    { id: 'poco-m2', name: 'Poco M2', brand: 'xiaomi' },
    { id: 'poco-c65', name: 'Poco C65', brand: 'xiaomi' },
    { id: 'poco-c55', name: 'Poco C55', brand: 'xiaomi' },
    { id: 'poco-c51', name: 'Poco C51', brand: 'xiaomi' },
    { id: 'poco-c50', name: 'Poco C50', brand: 'xiaomi' },
    { id: 'poco-c31', name: 'Poco C31', brand: 'xiaomi' },
    { id: 'poco-c3', name: 'Poco C3', brand: 'xiaomi' },

    // Mi Series
    { id: 'mi-11x', name: 'Mi 11X', brand: 'xiaomi' },
    { id: 'mi-11x-pro', name: 'Mi 11X Pro', brand: 'xiaomi' },
    { id: 'mi-11-lite', name: 'Mi 11 Lite', brand: 'xiaomi' },
    { id: 'mi-10i', name: 'Mi 10i', brand: 'xiaomi' },
    { id: 'mi-10t', name: 'Mi 10T', brand: 'xiaomi' },
    { id: 'mi-a3', name: 'Mi A3', brand: 'xiaomi' },
    { id: 'mi-a2', name: 'Mi A2', brand: 'xiaomi' },
    { id: 'mi-a1', name: 'Mi A1', brand: 'xiaomi' },

    // ================= VIVO =================
    // V Series
    { id: 'v30-pro', name: 'Vivo V30 Pro', brand: 'vivo' },
    { id: 'v30', name: 'Vivo V30', brand: 'vivo' },
    { id: 'v29-pro', name: 'Vivo V29 Pro', brand: 'vivo' },
    { id: 'v29', name: 'Vivo V29', brand: 'vivo' },
    { id: 'v29e', name: 'Vivo V29e', brand: 'vivo' },
    { id: 'v27-pro', name: 'Vivo V27 Pro', brand: 'vivo' },
    { id: 'v27', name: 'Vivo V27', brand: 'vivo' },
    { id: 'v25-pro', name: 'Vivo V25 Pro', brand: 'vivo' },
    { id: 'v25', name: 'Vivo V25', brand: 'vivo' },
    { id: 'v23-pro', name: 'Vivo V23 Pro', brand: 'vivo' },
    { id: 'v23', name: 'Vivo V23', brand: 'vivo' },
    { id: 'v21', name: 'Vivo V21', brand: 'vivo' },
    { id: 'v21e', name: 'Vivo V21e', brand: 'vivo' },
    { id: 'v20-pro', name: 'Vivo V20 Pro', brand: 'vivo' },
    { id: 'v20', name: 'Vivo V20', brand: 'vivo' },
    { id: 'v20-se', name: 'Vivo V20 SE', brand: 'vivo' },
    { id: 'v19', name: 'Vivo V19', brand: 'vivo' },
    { id: 'v17-pro', name: 'Vivo V17 Pro', brand: 'vivo' },
    { id: 'v17', name: 'Vivo V17', brand: 'vivo' },
    { id: 'v15-pro', name: 'Vivo V15 Pro', brand: 'vivo' },
    { id: 'v15', name: 'Vivo V15', brand: 'vivo' },
    { id: 'v11-pro', name: 'Vivo V11 Pro', brand: 'vivo' },
    { id: 'v9-pro', name: 'Vivo V9 Pro', brand: 'vivo' },
    { id: 'v9', name: 'Vivo V9', brand: 'vivo' },
    { id: 'v7-plus', name: 'Vivo V7 Plus', brand: 'vivo' },

    // Y Series
    { id: 'y200', name: 'Vivo Y200 5G', brand: 'vivo' },
    { id: 'y100', name: 'Vivo Y100', brand: 'vivo' },
    { id: 'y75', name: 'Vivo Y75', brand: 'vivo' },
    { id: 'y73', name: 'Vivo Y73', brand: 'vivo' },
    { id: 'y56', name: 'Vivo Y56 5G', brand: 'vivo' },
    { id: 'y36', name: 'Vivo Y36', brand: 'vivo' },
    { id: 'y35', name: 'Vivo Y35', brand: 'vivo' },
    { id: 'y33s', name: 'Vivo Y33s', brand: 'vivo' },
    { id: 'y22', name: 'Vivo Y22', brand: 'vivo' },
    { id: 'y21t', name: 'Vivo Y21T', brand: 'vivo' },
    { id: 'y21', name: 'Vivo Y21', brand: 'vivo' },
    { id: 'y20g', name: 'Vivo Y20G', brand: 'vivo' },
    { id: 'y20i', name: 'Vivo Y20i', brand: 'vivo' },
    { id: 'y20', name: 'Vivo Y20', brand: 'vivo' },
    { id: 'y19', name: 'Vivo Y19', brand: 'vivo' },
    { id: 'y17', name: 'Vivo Y17', brand: 'vivo' },
    { id: 'y16', name: 'Vivo Y16', brand: 'vivo' },
    { id: 'y15s', name: 'Vivo Y15s', brand: 'vivo' },
    { id: 'y15', name: 'Vivo Y15', brand: 'vivo' },
    { id: 'y12s', name: 'Vivo Y12s', brand: 'vivo' },
    { id: 'y12g', name: 'Vivo Y12G', brand: 'vivo' },
    { id: 'y12', name: 'Vivo Y12', brand: 'vivo' },
    { id: 'y11', name: 'Vivo Y11', brand: 'vivo' },
    { id: 'y95', name: 'Vivo Y95', brand: 'vivo' },
    { id: 'y93', name: 'Vivo Y93', brand: 'vivo' },
    { id: 'y91i', name: 'Vivo Y91i', brand: 'vivo' },
    { id: 'y91', name: 'Vivo Y91', brand: 'vivo' },
    { id: 'y83', name: 'Vivo Y83', brand: 'vivo' },
    { id: 'y81', name: 'Vivo Y81', brand: 'vivo' },
    { id: 'y71', name: 'Vivo Y71', brand: 'vivo' },
    { id: 'y53', name: 'Vivo Y53', brand: 'vivo' },

    // T Series
    { id: 't3', name: 'Vivo T3 5G', brand: 'vivo' },
    { id: 't2-pro', name: 'Vivo T2 Pro', brand: 'vivo' },
    { id: 't2x', name: 'Vivo T2x', brand: 'vivo' },
    { id: 't1-pro', name: 'Vivo T1 Pro', brand: 'vivo' },
    { id: 't1', name: 'Vivo T1 5G', brand: 'vivo' },
    { id: 't1-44w', name: 'Vivo T1 44W', brand: 'vivo' },

    // ================= OPPO =================
    // Reno Series
    { id: 'reno-11-pro', name: 'Oppo Reno 11 Pro', brand: 'oppo' },
    { id: 'reno-11', name: 'Oppo Reno 11', brand: 'oppo' },
    { id: 'reno-10-pro-plus', name: 'Oppo Reno 10 Pro+', brand: 'oppo' },
    { id: 'reno-10-pro', name: 'Oppo Reno 10 Pro', brand: 'oppo' },
    { id: 'reno-10', name: 'Oppo Reno 10', brand: 'oppo' },
    { id: 'reno-8-pro', name: 'Oppo Reno 8 Pro', brand: 'oppo' },
    { id: 'reno-8-t', name: 'Oppo Reno 8T', brand: 'oppo' },
    { id: 'reno-8', name: 'Oppo Reno 8', brand: 'oppo' },
    { id: 'reno-7-pro', name: 'Oppo Reno 7 Pro', brand: 'oppo' },
    { id: 'reno-7', name: 'Oppo Reno 7', brand: 'oppo' },
    { id: 'reno-6-pro', name: 'Oppo Reno 6 Pro', brand: 'oppo' },
    { id: 'reno-6', name: 'Oppo Reno 6', brand: 'oppo' },
    { id: 'reno-5-pro', name: 'Oppo Reno 5 Pro', brand: 'oppo' },
    { id: 'reno-4-pro', name: 'Oppo Reno 4 Pro', brand: 'oppo' },
    { id: 'reno-3-pro', name: 'Oppo Reno 3 Pro', brand: 'oppo' },
    { id: 'reno-2f', name: 'Oppo Reno 2F', brand: 'oppo' },
    { id: 'reno-2z', name: 'Oppo Reno 2Z', brand: 'oppo' },
    { id: 'reno-2', name: 'Oppo Reno 2', brand: 'oppo' },

    // F Series
    { id: 'f25-pro', name: 'Oppo F25 Pro', brand: 'oppo' },
    { id: 'f23', name: 'Oppo F23 5G', brand: 'oppo' },
    { id: 'f21s-pro', name: 'Oppo F21s Pro', brand: 'oppo' },
    { id: 'f21-pro', name: 'Oppo F21 Pro', brand: 'oppo' },
    { id: 'f19-pro-plus', name: 'Oppo F19 Pro+', brand: 'oppo' },
    { id: 'f19-pro', name: 'Oppo F19 Pro', brand: 'oppo' },
    { id: 'f19-s', name: 'Oppo F19s', brand: 'oppo' },
    { id: 'f19', name: 'Oppo F19', brand: 'oppo' },
    { id: 'f17-pro', name: 'Oppo F17 Pro', brand: 'oppo' },
    { id: 'f17', name: 'Oppo F17', brand: 'oppo' },
    { id: 'f15', name: 'Oppo F15', brand: 'oppo' },
    { id: 'f11-pro', name: 'Oppo F11 Pro', brand: 'oppo' },
    { id: 'f11', name: 'Oppo F11', brand: 'oppo' },
    { id: 'f9-pro', name: 'Oppo F9 Pro', brand: 'oppo' },
    { id: 'f9', name: 'Oppo F9', brand: 'oppo' },
    { id: 'f7', name: 'Oppo F7', brand: 'oppo' },
    { id: 'f5', name: 'Oppo F5', brand: 'oppo' },
    
    // A Series
    { id: 'a79', name: 'Oppo A79 5G', brand: 'oppo' },
    { id: 'a78-5g', name: 'Oppo A78 5G', brand: 'oppo' },
    { id: 'a78-4g', name: 'Oppo A78 4G', brand: 'oppo' },
    { id: 'a77s', name: 'Oppo A77s', brand: 'oppo' },
    { id: 'a77', name: 'Oppo A77', brand: 'oppo' },
    { id: 'a76', name: 'Oppo A76', brand: 'oppo' },
    { id: 'a74', name: 'Oppo A74 5G', brand: 'oppo' },
    { id: 'a59', name: 'Oppo A59 5G', brand: 'oppo' },
    { id: 'a58', name: 'Oppo A58', brand: 'oppo' },
    { id: 'a57', name: 'Oppo A57', brand: 'oppo' },
    { id: 'a55', name: 'Oppo A55', brand: 'oppo' },
    { id: 'a54', name: 'Oppo A54', brand: 'oppo' },
    { id: 'a53s', name: 'Oppo A53s 5G', brand: 'oppo' },
    { id: 'a53', name: 'Oppo A53', brand: 'oppo' },
    { id: 'a52', name: 'Oppo A52', brand: 'oppo' },
    { id: 'a38', name: 'Oppo A38', brand: 'oppo' },
    { id: 'a31', name: 'Oppo A31', brand: 'oppo' },
    { id: 'a18', name: 'Oppo A18', brand: 'oppo' },
    { id: 'a17k', name: 'Oppo A17k', brand: 'oppo' },
    { id: 'a17', name: 'Oppo A17', brand: 'oppo' },
    { id: 'a16k', name: 'Oppo A16k', brand: 'oppo' },
    { id: 'a16', name: 'Oppo A16', brand: 'oppo' },
    { id: 'a15s', name: 'Oppo A15s', brand: 'oppo' },
    { id: 'a15', name: 'Oppo A15', brand: 'oppo' },
    { id: 'a12', name: 'Oppo A12', brand: 'oppo' },
    { id: 'a11k', name: 'Oppo A11k', brand: 'oppo' },
    { id: 'a9-2020', name: 'Oppo A9 2020', brand: 'oppo' },
    { id: 'a5-2020', name: 'Oppo A5 2020', brand: 'oppo' },
    { id: 'a5s', name: 'Oppo A5s', brand: 'oppo' },
    { id: 'a3s', name: 'Oppo A3s', brand: 'oppo' },
    { id: 'a1k', name: 'Oppo A1k', brand: 'oppo' },

    // ================= REALME =================
    // Number Series
    { id: 'realme-12-pro-plus', name: 'Realme 12 Pro+', brand: 'realme' },
    { id: 'realme-12-pro', name: 'Realme 12 Pro', brand: 'realme' },
    { id: 'realme-12-plus', name: 'Realme 12+', brand: 'realme' },
    { id: 'realme-12', name: 'Realme 12', brand: 'realme' },
    { id: 'realme-11-pro-plus', name: 'Realme 11 Pro+', brand: 'realme' },
    { id: 'realme-11-pro', name: 'Realme 11 Pro', brand: 'realme' },
    { id: 'realme-11-x', name: 'Realme 11x 5G', brand: 'realme' },
    { id: 'realme-11', name: 'Realme 11 5G', brand: 'realme' },
    { id: 'realme-10-pro-plus', name: 'Realme 10 Pro+', brand: 'realme' },
    { id: 'realme-10-pro', name: 'Realme 10 Pro', brand: 'realme' },
    { id: 'realme-10', name: 'Realme 10', brand: 'realme' },
    { id: 'realme-9-pro-plus', name: 'Realme 9 Pro+', brand: 'realme' },
    { id: 'realme-9-pro', name: 'Realme 9 Pro', brand: 'realme' },
    { id: 'realme-9-se', name: 'Realme 9 SE', brand: 'realme' },
    { id: 'realme-9-5g', name: 'Realme 9 5G', brand: 'realme' },
    { id: 'realme-9i-5g', name: 'Realme 9i 5G', brand: 'realme' },
    { id: 'realme-9i', name: 'Realme 9i', brand: 'realme' },
    { id: 'realme-8-pro', name: 'Realme 8 Pro', brand: 'realme' },
    { id: 'realme-8', name: 'Realme 8', brand: 'realme' },
    { id: 'realme-8i', name: 'Realme 8i', brand: 'realme' },
    { id: 'realme-8s', name: 'Realme 8s 5G', brand: 'realme' },
    { id: 'realme-7-pro', name: 'Realme 7 Pro', brand: 'realme' },
    { id: 'realme-7', name: 'Realme 7', brand: 'realme' },
    { id: 'realme-7i', name: 'Realme 7i', brand: 'realme' },
    { id: 'realme-6-pro', name: 'Realme 6 Pro', brand: 'realme' },
    { id: 'realme-6', name: 'Realme 6', brand: 'realme' },
    { id: 'realme-6i', name: 'Realme 6i', brand: 'realme' },
    { id: 'realme-5-pro', name: 'Realme 5 Pro', brand: 'realme' },
    { id: 'realme-5', name: 'Realme 5', brand: 'realme' },
    { id: 'realme-5i', name: 'Realme 5i', brand: 'realme' },
    { id: 'realme-5s', name: 'Realme 5s', brand: 'realme' },
    { id: 'realme-3-pro', name: 'Realme 3 Pro', brand: 'realme' },
    { id: 'realme-3', name: 'Realme 3', brand: 'realme' },
    { id: 'realme-3i', name: 'Realme 3i', brand: 'realme' },
    { id: 'realme-2-pro', name: 'Realme 2 Pro', brand: 'realme' },
    { id: 'realme-2', name: 'Realme 2', brand: 'realme' },
    { id: 'realme-1', name: 'Realme 1', brand: 'realme' },

    // C Series
    { id: 'realme-c67', name: 'Realme C67 5G', brand: 'realme' },
    { id: 'realme-c55', name: 'Realme C55', brand: 'realme' },
    { id: 'realme-c53', name: 'Realme C53', brand: 'realme' },
    { id: 'realme-c51', name: 'Realme C51', brand: 'realme' },
    { id: 'realme-c35', name: 'Realme C35', brand: 'realme' },
    { id: 'realme-c33', name: 'Realme C33', brand: 'realme' },
    { id: 'realme-c31', name: 'Realme C31', brand: 'realme' },
    { id: 'realme-c30', name: 'Realme C30', brand: 'realme' },
    { id: 'realme-c25s', name: 'Realme C25s', brand: 'realme' },
    { id: 'realme-c25y', name: 'Realme C25Y', brand: 'realme' },
    { id: 'realme-c25', name: 'Realme C25', brand: 'realme' },
    { id: 'realme-c21y', name: 'Realme C21Y', brand: 'realme' },
    { id: 'realme-c21', name: 'Realme C21', brand: 'realme' },
    { id: 'realme-c20', name: 'Realme C20', brand: 'realme' },
    { id: 'realme-c15', name: 'Realme C15', brand: 'realme' },
    { id: 'realme-c12', name: 'Realme C12', brand: 'realme' },
    { id: 'realme-c11-2021', name: 'Realme C11 2021', brand: 'realme' },
    { id: 'realme-c11', name: 'Realme C11', brand: 'realme' },
    { id: 'realme-c3', name: 'Realme C3', brand: 'realme' },
    { id: 'realme-c2', name: 'Realme C2', brand: 'realme' },
    { id: 'realme-c1', name: 'Realme C1', brand: 'realme' },

    // Narzo / X / GT
    { id: 'narzo-60-pro', name: 'Realme Narzo 60 Pro', brand: 'realme' },
    { id: 'narzo-60', name: 'Realme Narzo 60', brand: 'realme' },
    { id: 'narzo-n55', name: 'Realme Narzo N55', brand: 'realme' },
    { id: 'narzo-n53', name: 'Realme Narzo N53', brand: 'realme' },
    { id: 'narzo-50-pro', name: 'Realme Narzo 50 Pro', brand: 'realme' },
    { id: 'narzo-50', name: 'Realme Narzo 50', brand: 'realme' },
    { id: 'narzo-50a', name: 'Realme Narzo 50A', brand: 'realme' },
    { id: 'narzo-50i', name: 'Realme Narzo 50i', brand: 'realme' },
    { id: 'narzo-30-pro', name: 'Realme Narzo 30 Pro', brand: 'realme' },
    { id: 'narzo-30', name: 'Realme Narzo 30', brand: 'realme' },
    { id: 'narzo-20-pro', name: 'Realme Narzo 20 Pro', brand: 'realme' },
    { id: 'narzo-20', name: 'Realme Narzo 20', brand: 'realme' },
    { id: 'narzo-10', name: 'Realme Narzo 10', brand: 'realme' },
    { id: 'narzo-10a', name: 'Realme Narzo 10A', brand: 'realme' },
    { id: 'realme-gt-2-pro', name: 'Realme GT 2 Pro', brand: 'realme' },
    { id: 'realme-gt-neo-3', name: 'Realme GT Neo 3', brand: 'realme' },
    { id: 'realme-gt-master', name: 'Realme GT Master', brand: 'realme' },
    { id: 'realme-xt', name: 'Realme XT', brand: 'realme' },
    { id: 'realme-x7-pro', name: 'Realme X7 Pro', brand: 'realme' },
    { id: 'realme-x7-max', name: 'Realme X7 Max', brand: 'realme' },
    { id: 'realme-x3-superzoom', name: 'Realme X3 SuperZoom', brand: 'realme' },
    { id: 'realme-x2-pro', name: 'Realme X2 Pro', brand: 'realme' },
    { id: 'realme-x2', name: 'Realme X2', brand: 'realme' },
    { id: 'realme-x', name: 'Realme X', brand: 'realme' },

    // ================= ONEPLUS =================
    { id: 'oneplus-12', name: 'OnePlus 12', brand: 'oneplus' },
    { id: 'oneplus-12r', name: 'OnePlus 12R', brand: 'oneplus' },
    { id: 'oneplus-11', name: 'OnePlus 11', brand: 'oneplus' },
    { id: 'oneplus-11r', name: 'OnePlus 11R', brand: 'oneplus' },
    { id: 'oneplus-10-pro', name: 'OnePlus 10 Pro', brand: 'oneplus' },
    { id: 'oneplus-10r', name: 'OnePlus 10R', brand: 'oneplus' },
    { id: 'oneplus-10t', name: 'OnePlus 10T', brand: 'oneplus' },
    { id: 'oneplus-9-pro', name: 'OnePlus 9 Pro', brand: 'oneplus' },
    { id: 'oneplus-9', name: 'OnePlus 9', brand: 'oneplus' },
    { id: 'oneplus-9r', name: 'OnePlus 9R', brand: 'oneplus' },
    { id: 'oneplus-9rt', name: 'OnePlus 9RT', brand: 'oneplus' },
    { id: 'oneplus-8t', name: 'OnePlus 8T', brand: 'oneplus' },
    { id: 'oneplus-8-pro', name: 'OnePlus 8 Pro', brand: 'oneplus' },
    { id: 'oneplus-8', name: 'OnePlus 8', brand: 'oneplus' },
    { id: 'oneplus-7t-pro', name: 'OnePlus 7T Pro', brand: 'oneplus' },
    { id: 'oneplus-7t', name: 'OnePlus 7T', brand: 'oneplus' },
    { id: 'oneplus-7-pro', name: 'OnePlus 7 Pro', brand: 'oneplus' },
    { id: 'oneplus-7', name: 'OnePlus 7', brand: 'oneplus' },
    { id: 'oneplus-6t', name: 'OnePlus 6T', brand: 'oneplus' },
    { id: 'oneplus-6', name: 'OnePlus 6', brand: 'oneplus' },
    { id: 'oneplus-5t', name: 'OnePlus 5T', brand: 'oneplus' },
    { id: 'oneplus-5', name: 'OnePlus 5', brand: 'oneplus' },
    { id: 'oneplus-3t', name: 'OnePlus 3T', brand: 'oneplus' },
    { id: 'nord-ce-4', name: 'OnePlus Nord CE 4', brand: 'oneplus' },
    { id: 'nord-3', name: 'OnePlus Nord 3', brand: 'oneplus' },
    { id: 'nord-ce-3', name: 'OnePlus Nord CE 3', brand: 'oneplus' },
    { id: 'nord-ce-3-lite', name: 'OnePlus Nord CE 3 Lite', brand: 'oneplus' },
    { id: 'nord-2t', name: 'OnePlus Nord 2T', brand: 'oneplus' },
    { id: 'nord-2', name: 'OnePlus Nord 2', brand: 'oneplus' },
    { id: 'nord-ce-2', name: 'OnePlus Nord CE 2', brand: 'oneplus' },
    { id: 'nord-ce-2-lite', name: 'OnePlus Nord CE 2 Lite', brand: 'oneplus' },
    { id: 'nord-ce', name: 'OnePlus Nord CE', brand: 'oneplus' },
    { id: 'nord', name: 'OnePlus Nord', brand: 'oneplus' },

    // ================= MOTOROLA =================
    { id: 'moto-edge-40-neo', name: 'Moto Edge 40 Neo', brand: 'motorola' },
    { id: 'moto-edge-40', name: 'Moto Edge 40', brand: 'motorola' },
    { id: 'moto-g84', name: 'Moto G84', brand: 'motorola' },
    { id: 'moto-g54', name: 'Moto G54', brand: 'motorola' },
    { id: 'moto-g34', name: 'Moto G34 5G', brand: 'motorola' },
    { id: 'moto-g32', name: 'Moto G32', brand: 'motorola' },
    { id: 'moto-g62', name: 'Moto G62', brand: 'motorola' },
    { id: 'moto-g52', name: 'Moto G52', brand: 'motorola' },
    { id: 'moto-g42', name: 'Moto G42', brand: 'motorola' },
    { id: 'moto-e13', name: 'Moto E13', brand: 'motorola' },
    { id: 'moto-one-fusion', name: 'Moto One Fusion+', brand: 'motorola' },
    { id: 'moto-one-power', name: 'Moto One Power', brand: 'motorola' },

    // ================= GOOGLE =================
    { id: 'pixel-8-pro', name: 'Google Pixel 8 Pro', brand: 'google' },
    { id: 'pixel-8', name: 'Google Pixel 8', brand: 'google' },
    { id: 'pixel-7a', name: 'Google Pixel 7a', brand: 'google' },
    { id: 'pixel-7-pro', name: 'Google Pixel 7 Pro', brand: 'google' },
    { id: 'pixel-7', name: 'Google Pixel 7', brand: 'google' },
    { id: 'pixel-6a', name: 'Google Pixel 6a', brand: 'google' },
    { id: 'pixel-6-pro', name: 'Google Pixel 6 Pro', brand: 'google' },
    { id: 'pixel-6', name: 'Google Pixel 6', brand: 'google' },
    { id: 'pixel-4a', name: 'Google Pixel 4a', brand: 'google' },

    // ================= NOTHING =================
    { id: 'nothing-phone-2', name: 'Nothing Phone (2)', brand: 'nothing' },
    { id: 'nothing-phone-2a', name: 'Nothing Phone (2a)', brand: 'nothing' },
    { id: 'nothing-phone-1', name: 'Nothing Phone (1)', brand: 'nothing' },

    // ================= INFINIX =================
    { id: 'infinix-gt-10-pro', name: 'Infinix GT 10 Pro', brand: 'infinix' },
    { id: 'infinix-note-30', name: 'Infinix Note 30 5G', brand: 'infinix' },
    { id: 'infinix-note-12', name: 'Infinix Note 12', brand: 'infinix' },
    { id: 'infinix-hot-30', name: 'Infinix Hot 30', brand: 'infinix' },
    { id: 'infinix-hot-20', name: 'Infinix Hot 20 5G', brand: 'infinix' },
    { id: 'infinix-hot-12', name: 'Infinix Hot 12', brand: 'infinix' },
    { id: 'infinix-hot-11', name: 'Infinix Hot 11', brand: 'infinix' },
    { id: 'infinix-hot-10', name: 'Infinix Hot 10', brand: 'infinix' },
    { id: 'infinix-hot-9', name: 'Infinix Hot 9', brand: 'infinix' },
    { id: 'infinix-smart-8', name: 'Infinix Smart 8', brand: 'infinix' },
    { id: 'infinix-smart-7', name: 'Infinix Smart 7', brand: 'infinix' },
    { id: 'infinix-smart-6', name: 'Infinix Smart 6', brand: 'infinix' },

    // ================= TECNO =================
    { id: 'tecno-spark-20', name: 'Tecno Spark 20', brand: 'tecno' },
    { id: 'tecno-spark-10', name: 'Tecno Spark 10 5G', brand: 'tecno' },
    { id: 'tecno-spark-go', name: 'Tecno Spark Go', brand: 'tecno' },
    { id: 'tecno-pova-5', name: 'Tecno Pova 5', brand: 'tecno' },
    { id: 'tecno-pova-4', name: 'Tecno Pova 4', brand: 'tecno' },
    { id: 'tecno-camon-20', name: 'Tecno Camon 20', brand: 'tecno' },
    { id: 'tecno-camon-19', name: 'Tecno Camon 19', brand: 'tecno' },
];
